all:
	g++ -o password1 password1.cpp -g -w
	g++ -o password2 password2.cpp -g -w
	g++ -o password3 password3.cpp -g -w
	g++ -o stack_safety stack_safety.cpp -g -w

clean:
	rm -f password1 password2 password3 stack_safety
