all:
	g++ -o asio asio.cpp -I/mnt/eclipse/acg/users/delozier/git/boost_1_59_0/ /mnt/eclipse/acg/users/delozier/git/boost_1_59_0/stage/lib/libboost_system.a -pthread
	g++ -o server server.cpp
	g++ -o client client.cpp
