all: if_statements debugging	

if_statements: if_statements.cpp
	g++ -o if_statements if_statements.cpp

debugging: debugging.cpp
	g++ -o debugging debugging.cpp -g

clean:
	rm if_statements simple_arrays debugging
